name: dogma_drone_api
version: 0.0.1
description: API client for the Drone Continuous Integration Service.
environment:
  sdk: '>=1.12.0-dev.4.0 <2.0.0'
dependencies:
  dogma_convert: '^0.0.1'
  dogma_rest_client: '^0.0.1'
  dogma_rest_connection: '^0.0.1'
  uri: '^0.11.0'
dev_dependencies:
  dogma_swagger:
    path: ../dogma-swagger
  test: '^0.12.5+1'
